-- ============================================================================
-- Migration: Create Forecasts Table
-- Description: Demand predictions generated by the Python forecasting module.
--              One row per device per store per forecast period.
--              store_id = NULL means a company-wide (global) forecast.
-- ============================================================================

CREATE TABLE forecasts (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id          UUID NOT NULL REFERENCES devices(id),
  store_id           UUID REFERENCES stores(id),
  forecast_period    DATE NOT NULL,   -- first day of the forecasted month, e.g. '2026-05-01'
  predicted_quantity INTEGER NOT NULL,
  actual_quantity    INTEGER,          -- filled after the period ends for accuracy comparison
  confidence_score   NUMERIC(5,2),    -- percentage, e.g. 85.50
  model_version      TEXT,            -- e.g. 'v1.0-linear'
  notes              TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT chk_forecasts_predicted_non_negative CHECK (predicted_quantity >= 0),
  CONSTRAINT chk_forecasts_actual_non_negative    CHECK (actual_quantity >= 0),
  CONSTRAINT chk_forecasts_confidence_range       CHECK (confidence_score BETWEEN 0 AND 100)
);

-- Prevent duplicate forecasts for same device + store + period
-- This handles the case where store_id IS NOT NULL
CREATE UNIQUE INDEX uq_forecasts_device_store_period
  ON forecasts (device_id, store_id, forecast_period)
  WHERE store_id IS NOT NULL;

-- Separate unique index for global forecasts (store_id IS NULL)
-- because NULL != NULL in standard unique constraints
CREATE UNIQUE INDEX uq_forecasts_device_global_period
  ON forecasts (device_id, forecast_period)
  WHERE store_id IS NULL;

CREATE INDEX idx_forecasts_device_id ON forecasts(device_id);
CREATE INDEX idx_forecasts_store_id ON forecasts(store_id);
CREATE INDEX idx_forecasts_period ON forecasts(forecast_period);
CREATE INDEX idx_forecasts_device_period ON forecasts(device_id, forecast_period);
